AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role with Samarth Policy

Resources:
  SamarthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: samarth-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      
  SamarthPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: samarth
      Roles:
        - Ref: SamarthRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: '*'
            Resource: 'arn:aws:s3:::new-s3-bucket-24-12-2024'